// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiempo_libre.Models;

#nullable disable

namespace tiempo_libre.Migrations
{
    [DbContext(typeof(FreeTimeDbContext))]
    [Migration("20250912232512_AddProgramacionesAnualesModel")]
    partial class AddProgramacionesAnualesModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrupoSindicalizado", b =>
                {
                    b.Property<int>("GruposGrupoId")
                        .HasColumnType("int");

                    b.Property<int>("SindicalizadosSindicalizadoId")
                        .HasColumnType("int");

                    b.HasKey("GruposGrupoId", "SindicalizadosSindicalizadoId");

                    b.HasIndex("SindicalizadosSindicalizadoId");

                    b.ToTable("GrupoSindicalizado");
                });

            modelBuilder.Entity("RolUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("tiempo_libre.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<int?>("JefeId")
                        .HasColumnType("int");

                    b.Property<int?>("JefeSuplenteId")
                        .HasColumnType("int");

                    b.Property<string>("NombreGeneral")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnidadOrganizativaSap")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AreaId")
                        .HasName("PK__Areas__70B82048C119927A");

                    b.HasIndex("JefeId");

                    b.HasIndex("JefeSuplenteId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("tiempo_libre.Models.CalendarioPorEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioFecha")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetallesDiaInhabil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaDeLaSemana")
                        .HasColumnType("int");

                    b.Property<int>("DiaFecha")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaDelDia")
                        .HasColumnType("date");

                    b.Property<int?>("IdDiaInhabil")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int?>("IdIncidenciaOPermiso")
                        .HasColumnType("int");

                    b.Property<int>("IdRegla")
                        .HasColumnType("int");

                    b.Property<int>("IdTurnoXRolSemanalXRegla")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioEmpleadoSindicalizado")
                        .HasColumnType("int");

                    b.Property<int?>("IdVacaciones")
                        .HasColumnType("int");

                    b.Property<int>("MesFecha")
                        .HasColumnType("int");

                    b.Property<int>("NominaEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("TipoActividadDelDia")
                        .HasColumnType("int");

                    b.Property<int?>("TipoDeIncedencia")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnioFecha");

                    b.HasIndex("DiaFecha");

                    b.HasIndex("FechaDelDia");

                    b.HasIndex("IdDiaInhabil");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdIncidenciaOPermiso");

                    b.HasIndex("IdRegla");

                    b.HasIndex("IdTurnoXRolSemanalXRegla");

                    b.HasIndex("IdUsuarioEmpleadoSindicalizado");

                    b.HasIndex("IdVacaciones");

                    b.HasIndex("MesFecha");

                    b.HasIndex("NominaEmpleado");

                    b.ToTable("CalendarioPorEmpleados");
                });

            modelBuilder.Entity("tiempo_libre.Models.DiasInhabiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioFechaFinal")
                        .HasColumnType("int");

                    b.Property<int>("AnioFechaInicial")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DiaFechaFinal")
                        .HasColumnType("int");

                    b.Property<int>("DiaFechaInicial")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicial")
                        .HasColumnType("date");

                    b.Property<int>("MesFechaFinal")
                        .HasColumnType("int");

                    b.Property<int>("MesFechaInicial")
                        .HasColumnType("int");

                    b.Property<int>("TipoActividadDelDia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnioFechaFinal");

                    b.HasIndex("AnioFechaInicial");

                    b.HasIndex("DiaFechaFinal");

                    b.HasIndex("DiaFechaInicial");

                    b.HasIndex("Fecha");

                    b.HasIndex("MesFechaFinal");

                    b.HasIndex("MesFechaInicial");

                    b.ToTable("DiasInhabiles");
                });

            modelBuilder.Entity("tiempo_libre.Models.Empleado", b =>
                {
                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<int?>("CentroCoste")
                        .HasColumnType("int");

                    b.Property<string>("EncargadoRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Posicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnidadOrganizativa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Nomina")
                        .HasName("PK__Empleado__765BE2D8758F406A");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("tiempo_libre.Models.Grupo", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("DuracionDeturno")
                        .HasColumnType("int");

                    b.Property<string>("IdentificadorSAP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LiderId")
                        .HasColumnType("int");

                    b.Property<int?>("LiderSuplenteId")
                        .HasColumnType("int");

                    b.Property<int>("PersonasPorTurno")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GrupoId")
                        .HasName("PK__Grupos__556BF040AD6A4924");

                    b.HasIndex("AreaId");

                    b.HasIndex("LiderId");

                    b.HasIndex("LiderSuplenteId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("tiempo_libre.Models.IncidenciaOPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioFechaFinal")
                        .HasColumnType("int");

                    b.Property<int>("AnioFechaInicial")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DiaDeLaSemana")
                        .HasColumnType("int");

                    b.Property<int>("DiaFechaFinal")
                        .HasColumnType("int");

                    b.Property<int>("DiaFechaInicial")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicial")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegla")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioAutoiza")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioSindicato")
                        .HasColumnType("int");

                    b.Property<int>("MesFechaFinal")
                        .HasColumnType("int");

                    b.Property<int>("MesFechaInicial")
                        .HasColumnType("int");

                    b.Property<int>("NominaEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("TiposDeIncedencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnioFechaInicial");

                    b.HasIndex("DiaFechaInicial");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdRegla");

                    b.HasIndex("IdUsuarioAutoiza");

                    b.HasIndex("IdUsuarioEmpleado");

                    b.HasIndex("IdUsuarioSindicato");

                    b.HasIndex("MesFechaInicial");

                    b.HasIndex("NominaEmpleado");

                    b.ToTable("IncidenciasOPermisos");
                });

            modelBuilder.Entity("tiempo_libre.Models.LoggerAcciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdArea")
                        .HasColumnType("int");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCompletoUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("NominaUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LoggerAcciones");
                });

            modelBuilder.Entity("tiempo_libre.Models.PermisosEincapacidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClAbPre")
                        .HasColumnType("int");

                    b.Property<string>("ClaseAbsentismo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("Desde")
                        .HasColumnType("date");

                    b.Property<double?>("DiaNat")
                        .HasColumnType("float");

                    b.Property<double?>("Dias")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Permisos__3214EC27F814167F");

                    b.ToTable("PermisosEIncapacidades", (string)null);
                });

            modelBuilder.Entity("tiempo_libre.Models.ProgramacionesAnuales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalles")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTermina")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSuperUser")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdSuperUser");

                    b.ToTable("ProgramacionesAnuales");
                });

            modelBuilder.Entity("tiempo_libre.Models.Regla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("NumDeGrupos")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("ReglaEnumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReglaEnumId")
                        .IsUnique();

                    b.ToTable("Reglas");
                });

            modelBuilder.Entity("tiempo_libre.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("tiempo_libre.Models.RolInicialPorEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("RolSemanal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nomina");

                    b.ToTable("RolesInicialesPorEmpleado");
                });

            modelBuilder.Entity("tiempo_libre.Models.RolSemanal", b =>
                {
                    b.Property<int>("RolSemanalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolSemanalId"));

                    b.Property<int>("IdRegla")
                        .HasColumnType("int");

                    b.Property<int>("IndiceSemana")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("RolSemanalId");

                    b.HasIndex("IdRegla");

                    b.ToTable("RolesSemanales");
                });

            modelBuilder.Entity("tiempo_libre.Models.RolesEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CentroDeCoste")
                        .HasColumnType("int");

                    b.Property<string>("Dia")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("EncTiempos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Phtd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PHTD");

                    b.Property<string>("TextoPlanHrTrDia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__RolesEmp__3214EC2740992AEF");

                    b.ToTable("RolesEmpleados");
                });

            modelBuilder.Entity("tiempo_libre.Models.Sindicalizado", b =>
                {
                    b.Property<int>("SindicalizadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SindicalizadoId"));

                    b.Property<int?>("CentroCoste")
                        .HasColumnType("int");

                    b.Property<string>("EncargadoRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SindicalizadoId");

                    b.ToTable("Sindicalizado");
                });

            modelBuilder.Entity("tiempo_libre.Models.TurnoXRolSemanalXRegla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadDelDia")
                        .HasColumnType("int");

                    b.Property<int>("DiaDeLaSemana")
                        .HasColumnType("int");

                    b.Property<int>("IdRegla")
                        .HasColumnType("int");

                    b.Property<int>("IdRolSemanal")
                        .HasColumnType("int");

                    b.Property<int>("IndicePorRegla")
                        .HasColumnType("int");

                    b.Property<int?>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdRegla");

                    b.HasIndex("IdRolSemanal");

                    b.ToTable("TurnosXRolSemanalXRegla");
                });

            modelBuilder.Entity("tiempo_libre.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AntiguedadEnAnios")
                        .HasColumnType("int");

                    b.Property<int?>("AntiguedadEnDias")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("CentroCoste")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DiasDeVacacionesAsignados")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Maquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VacacionesPorAntiguedadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacacionesPorAntiguedadId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("tiempo_libre.Models.Vacaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadDelDia")
                        .HasColumnType("int");

                    b.Property<int>("AnioFecha")
                        .HasColumnType("int");

                    b.Property<bool>("AsignadaPorJefe")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("DiaFecha")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdTurnoXRolSemanalXRegla")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioEmpleadoSindicalizado")
                        .HasColumnType("int");

                    b.Property<int>("MesFecha")
                        .HasColumnType("int");

                    b.Property<int>("NominaEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("TurnoCubria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnioFecha");

                    b.HasIndex("DiaFecha");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdTurnoXRolSemanalXRegla");

                    b.HasIndex("IdUsuarioEmpleadoSindicalizado");

                    b.HasIndex("MesFecha");

                    b.HasIndex("NominaEmpleado");

                    b.ToTable("Vacaciones");
                });

            modelBuilder.Entity("tiempo_libre.Models.VacacionesPorAntiguedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AntiguedadEnAniosRangoFinal")
                        .HasColumnType("int");

                    b.Property<int>("AntiguedadEnAniosRangoInicial")
                        .HasColumnType("int");

                    b.Property<int>("DiasAsignadosPorContinental")
                        .HasColumnType("int");

                    b.Property<int>("DiasParaAsignarAutomaticamente")
                        .HasColumnType("int");

                    b.Property<int>("DiasPorEscogerPorEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("TotalDiasDeVacaciones")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VacacionesPorAntiguedad");
                });

            modelBuilder.Entity("GrupoSindicalizado", b =>
                {
                    b.HasOne("tiempo_libre.Models.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GruposGrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.Sindicalizado", null)
                        .WithMany()
                        .HasForeignKey("SindicalizadosSindicalizadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolUser", b =>
                {
                    b.HasOne("tiempo_libre.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tiempo_libre.Models.Area", b =>
                {
                    b.HasOne("tiempo_libre.Models.User", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Area_Jefe");

                    b.HasOne("tiempo_libre.Models.User", "JefeSuplente")
                        .WithMany()
                        .HasForeignKey("JefeSuplenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Area_JefeSuplente");

                    b.Navigation("Jefe");

                    b.Navigation("JefeSuplente");
                });

            modelBuilder.Entity("tiempo_libre.Models.CalendarioPorEmpleado", b =>
                {
                    b.HasOne("tiempo_libre.Models.DiasInhabiles", "DiaInhabil")
                        .WithMany()
                        .HasForeignKey("IdDiaInhabil")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tiempo_libre.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.IncidenciaOPermiso", "IncidenciaOPermiso")
                        .WithMany()
                        .HasForeignKey("IdIncidenciaOPermiso")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tiempo_libre.Models.Regla", "Regla")
                        .WithMany()
                        .HasForeignKey("IdRegla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.TurnoXRolSemanalXRegla", "TurnoXRolSemanalXRegla")
                        .WithMany()
                        .HasForeignKey("IdTurnoXRolSemanalXRegla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.User", "UsuarioEmpleadoSindicalizado")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEmpleadoSindicalizado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.Vacaciones", "Vacaciones")
                        .WithMany()
                        .HasForeignKey("IdVacaciones")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DiaInhabil");

                    b.Navigation("Grupo");

                    b.Navigation("IncidenciaOPermiso");

                    b.Navigation("Regla");

                    b.Navigation("TurnoXRolSemanalXRegla");

                    b.Navigation("UsuarioEmpleadoSindicalizado");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("tiempo_libre.Models.Grupo", b =>
                {
                    b.HasOne("tiempo_libre.Models.Area", "Area")
                        .WithMany("Grupos")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Grupos_Areas");

                    b.HasOne("tiempo_libre.Models.User", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Grupo_Lider");

                    b.HasOne("tiempo_libre.Models.User", "LiderSuplente")
                        .WithMany()
                        .HasForeignKey("LiderSuplenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Grupo_LiderSuplente");

                    b.Navigation("Area");

                    b.Navigation("Lider");

                    b.Navigation("LiderSuplente");
                });

            modelBuilder.Entity("tiempo_libre.Models.IncidenciaOPermiso", b =>
                {
                    b.HasOne("tiempo_libre.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tiempo_libre.Models.Regla", "Regla")
                        .WithMany()
                        .HasForeignKey("IdRegla")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tiempo_libre.Models.User", "UsuarioAutoriza")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAutoiza")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.User", "UsuarioEmpleado")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.User", "UsuarioSindicato")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSindicato")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupo");

                    b.Navigation("Regla");

                    b.Navigation("UsuarioAutoriza");

                    b.Navigation("UsuarioEmpleado");

                    b.Navigation("UsuarioSindicato");
                });

            modelBuilder.Entity("tiempo_libre.Models.LoggerAcciones", b =>
                {
                    b.HasOne("tiempo_libre.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tiempo_libre.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tiempo_libre.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Grupo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tiempo_libre.Models.ProgramacionesAnuales", b =>
                {
                    b.HasOne("tiempo_libre.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdSuperUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("tiempo_libre.Models.RolSemanal", b =>
                {
                    b.HasOne("tiempo_libre.Models.Regla", "Regla")
                        .WithMany("RolesSemanales")
                        .HasForeignKey("IdRegla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolSemanal_Regla");

                    b.Navigation("Regla");
                });

            modelBuilder.Entity("tiempo_libre.Models.TurnoXRolSemanalXRegla", b =>
                {
                    b.HasOne("tiempo_libre.Models.Regla", "Regla")
                        .WithMany("TurnosXRolSemanalXRegla")
                        .HasForeignKey("IdRegla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.RolSemanal", "RolSemanal")
                        .WithMany()
                        .HasForeignKey("IdRolSemanal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regla");

                    b.Navigation("RolSemanal");
                });

            modelBuilder.Entity("tiempo_libre.Models.User", b =>
                {
                    b.HasOne("tiempo_libre.Models.VacacionesPorAntiguedad", "VacacionesPorAntiguedad")
                        .WithMany("Users")
                        .HasForeignKey("VacacionesPorAntiguedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_User_VacacionesPorAntiguedad");

                    b.Navigation("VacacionesPorAntiguedad");
                });

            modelBuilder.Entity("tiempo_libre.Models.Vacaciones", b =>
                {
                    b.HasOne("tiempo_libre.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.TurnoXRolSemanalXRegla", "TurnoXRolSemanalXRegla")
                        .WithMany()
                        .HasForeignKey("IdTurnoXRolSemanalXRegla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.User", "UsuarioEmpleadoSindicalizado")
                        .WithMany()
                        .HasForeignKey("IdUsuarioEmpleadoSindicalizado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Vacaciones_UsuarioEmpleadoSindicalizado");

                    b.Navigation("Grupo");

                    b.Navigation("TurnoXRolSemanalXRegla");

                    b.Navigation("UsuarioEmpleadoSindicalizado");
                });

            modelBuilder.Entity("tiempo_libre.Models.Area", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("tiempo_libre.Models.Regla", b =>
                {
                    b.Navigation("RolesSemanales");

                    b.Navigation("TurnosXRolSemanalXRegla");
                });

            modelBuilder.Entity("tiempo_libre.Models.VacacionesPorAntiguedad", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
