// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiempo_libre.Models;

#nullable disable

namespace tiempo_libre.Migrations
{
    [DbContext(typeof(FreeTimeDbContext))]
    [Migration("20250822055352_AddExtraDataForGrupo")]
    partial class AddExtraDataForGrupo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("SindicalizadosPorGrupo", b =>
                {
                    b.Property<int>("SindicalizadoId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("SindicalizadoId", "GrupoId")
                        .HasName("PK__Empleado__80DD5614D5A43EBC");

                    b.HasIndex("GrupoId");

                    b.ToTable("SindicalizadosPorGrupo", (string)null);
                });

            modelBuilder.Entity("tiempo_libre.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<int?>("JefeId")
                        .HasColumnType("int");

                    b.Property<int?>("JefeSuplenteId")
                        .HasColumnType("int");

                    b.Property<string>("NombreGeneral")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnidadOrganizativaSap")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AreaId")
                        .HasName("PK__Areas__70B82048C119927A");

                    b.HasIndex("JefeId");

                    b.HasIndex("JefeSuplenteId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("tiempo_libre.Models.Empleado", b =>
                {
                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<int?>("CentroCoste")
                        .HasColumnType("int");

                    b.Property<string>("EncargadoRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Posicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnidadOrganizativa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Nomina")
                        .HasName("PK__Empleado__765BE2D8758F406A");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("tiempo_libre.Models.Grupo", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("DuracionDeturno")
                        .HasColumnType("int");

                    b.Property<string>("IdentificadorSAP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LiderId")
                        .HasColumnType("int");

                    b.Property<int?>("LiderSuplenteId")
                        .HasColumnType("int");

                    b.Property<int>("PersonasPorTurno")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GrupoId")
                        .HasName("PK__Grupos__556BF040AD6A4924");

                    b.HasIndex("AreaId");

                    b.HasIndex("LiderId");

                    b.HasIndex("LiderSuplenteId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("tiempo_libre.Models.PermisosEincapacidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClAbPre")
                        .HasColumnType("int");

                    b.Property<string>("ClaseAbsentismo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("Desde")
                        .HasColumnType("date");

                    b.Property<double?>("DiaNat")
                        .HasColumnType("float");

                    b.Property<double?>("Dias")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Permisos__3214EC27F814167F");

                    b.ToTable("PermisosEIncapacidades", (string)null);
                });

            modelBuilder.Entity("tiempo_libre.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("tiempo_libre.Models.RolesEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CentroDeCoste")
                        .HasColumnType("int");

                    b.Property<string>("Dia")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("EncTiempos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Phtd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PHTD");

                    b.Property<string>("TextoPlanHrTrDia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__RolesEmp__3214EC2740992AEF");

                    b.ToTable("RolesEmpleados");
                });

            modelBuilder.Entity("tiempo_libre.Models.Sindicalizado", b =>
                {
                    b.Property<int>("SindicalizadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SindicalizadoId"));

                    b.Property<int?>("CentroCoste")
                        .HasColumnType("int");

                    b.Property<string>("EncargadoRegistro")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Nomina")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SindicalizadoId")
                        .HasName("PK__Sindical__958BE91075C969C4");

                    b.HasIndex(new[] { "Nomina" }, "UQ__Sindical__765BE2D9A52A48AC")
                        .IsUnique();

                    b.ToTable("Sindicalizados");
                });

            modelBuilder.Entity("tiempo_libre.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RolUser", b =>
                {
                    b.HasOne("tiempo_libre.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiempo_libre.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SindicalizadosPorGrupo", b =>
                {
                    b.HasOne("tiempo_libre.Models.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .IsRequired()
                        .HasConstraintName("FK_EmpleadosPorGrupo_Grupos");

                    b.HasOne("tiempo_libre.Models.Sindicalizado", null)
                        .WithMany()
                        .HasForeignKey("SindicalizadoId")
                        .IsRequired()
                        .HasConstraintName("FK_EmpleadosPorGrupo_Empleados");
                });

            modelBuilder.Entity("tiempo_libre.Models.Area", b =>
                {
                    b.HasOne("tiempo_libre.Models.User", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Area_Jefe");

                    b.HasOne("tiempo_libre.Models.User", "JefeSuplente")
                        .WithMany()
                        .HasForeignKey("JefeSuplenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Area_JefeSuplente");

                    b.Navigation("Jefe");

                    b.Navigation("JefeSuplente");
                });

            modelBuilder.Entity("tiempo_libre.Models.Grupo", b =>
                {
                    b.HasOne("tiempo_libre.Models.Area", "Area")
                        .WithMany("Grupos")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Grupos_Areas");

                    b.HasOne("tiempo_libre.Models.User", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Grupo_Lider");

                    b.HasOne("tiempo_libre.Models.User", "LiderSuplente")
                        .WithMany()
                        .HasForeignKey("LiderSuplenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Grupo_LiderSuplente");

                    b.Navigation("Area");

                    b.Navigation("Lider");

                    b.Navigation("LiderSuplente");
                });

            modelBuilder.Entity("tiempo_libre.Models.Area", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
